#!/usr/bin/env node

'use strict';

module.exports = {
	"color":{
		"modules":[
			"BackgroundColor",
			"BorderColor",
			"HoverColor",
			"TextColor"
		],
		"naming":{
			"backgroundColor":"bg-",
			"textColor":"",
			"borderColor":"b--",
			"hover":"hover-"
		},
		"colors":[
			{"black": "#000"},
			{"near-black": "#111"},
			{"dark-gray": "#333"},
			{"mid-gray": "#555"},
			{"gray": "#777"},
			{"silver": "#999"},
			{"light-silver": "#aaa"},
			{"moon-gray": "#ccc"},
			{"light-gray": "#eee"},
			{"near-white": "#f4f4f4"},
			{"white": "#fff"},
			{"black-90": "rgba(0,0,0,.9)"},
			{"black-80": "rgba(0,0,0,.8)"},
			{"black-70": "rgba(0,0,0,.7)"},
			{"black-60": "rgba(0,0,0,.6)"},
			{"black-50": "rgba(0,0,0,.5)"},
			{"black-40": "rgba(0,0,0,.4)"},
			{"black-30": "rgba(0,0,0,.3)"},
			{"black-20": "rgba(0,0,0,.2)"},
			{"black-10": "rgba(0,0,0,.1)"},
			{"black-05": "rgba(0,0,0,.05)"},
			{"black-025": "rgba(0,0,0,.025)"},
			{"black-0125": "rgba(0,0,0,.0125)"},
			{"white-90": "rgba(255,255,255,.9)"},
			{"white-80": "rgba(255,255,255,.8)"},
			{"white-70": "rgba(255,255,255,.7)"},
			{"white-60": "rgba(255,255,255,.6)"},
			{"white-50": "rgba(255,255,255,.5)"},
			{"white-40": "rgba(255,255,255,.4)"},
			{"white-30": "rgba(255,255,255,.3)"},
			{"white-20": "rgba(255,255,255,.2)"},
			{"white-10": "rgba(255,255,255,.1)"},
			{"white-05": "rgba(255,255,255,.05)"},
			{"white-025": "rgba(255,255,255,.025)"},
			{"white-0125": "rgba(255,255,255,.0125)"},
			{"dark-red": "#e7040f"},
			{"red": "#ff4136"},
			{"light-red": "#ff725c"},
			{"orange": "#ff6300"},
			{"gold": "#ffb700"},
			{"yellow": "#ffd700"},
			{"light-yellow": "#fbf1a9"},
			{"purple": "#5e2ca5"},
			{"light-purple": "#a463f2"},
			{"dark-pink": "#d5008f"},
			{"hot-pink": "#ff41b4"},
			{"pink": "#ff80cc"},
			{"light-pink": "#ffa3d7"},
			{"dark-green": "#137752"},
			{"green": "#19a974"},
			{"light-green": "#9eebcf"},
			{"navy": "#001b44"},
			{"dark-blue": "#00449e"},
			{"blue": "#357edd"},
			{"light-blue": "#96ccff"},
			{"lightest-blue": "#cdecff"},
			{"washed-blue": "#f6fffe"},
			{"washed-green": "#e8fdf5"},
			{"washed-yellow": "#fffceb"},
			{"washed-red": "#ffdfdf"}
		]
	},
	"typography":{
		"modules":[
			"Font",
			"LetterSpacing",
			"LineHeight",
			"TypeScale",
			"TextAlign",
			"WhiteSpace",
			"WordBreaks"
		],
		"naming":{
			"sans":"sans-serif",
			"serif":"serif",
			"mono":"code",
			"bold":"b",
			"normal":"normal",
			"italic":"i",
			"scale":["f-headline","f-subheadline","f1","f2","f3","f4","f5","f6","f7"],
			"weight":"fw",
			"height":["lh-solid","lh-title","lh-copy"],
			"spacing":["tracked-tight","tracked","tracked-mega"],
			"align":{"left":"tl","center":"tc","right":"tr","justify":"tj"},
			"decoration":{"underline":"underline","linethrough":"strike","none":"no-underline"},
			"transform":{"capitalize":"ttc","uppercase":"ttu","lowercase":"ttl","none":"ttn"},
			"wordbreaks":{"normal":"word-normal","wrap":"word-wrap","nowrap":"word-nowrap"},
			"whitespace":{"normal":"ws-normal","nowrap":"nowrap","pre":"pre"}
		},
		"styles":{
			"sans":"-apple-system, BlinkMacSystemFont,'avenir next', avenir,helvetica, 'helvetica neue',ubuntu,roboto,noto,'segoe ui',arial",
			"serif":"georgia",
			"mono":"consolas, monaco",
			"fonts":[
				{"courier":"'Courier Next', courier, monospace"},
				{"helvetica":"'helvetica neue', helvetica,sans-serif"},
				{"avenir":"'avenir next', avenir,sans-serif"},
				{"athelas":"athelas,georgia,serif"},
				{"georgia":"georgia,serif"},
				{"times":"times,serif"},
				{"bodoni":"\"Bodoni MT\", serif"},
				{"calisto":"\"Calisto MT\", serif"},
				{"garamond":"garamond,serif"},
				{"baskerville":"baskerville,serif"}
			],
			"scale":["6rem","5rem","3rem","2.25rem","1.5rem","1.25rem","1rem",".875rem",".75rem"],
			"weights":["100","200","300","400","500","600","700","800","900"],
			"heights":["1","1.25","1.5"],
			"headline":"6rem",
			"subheadline":"5rem",
			"spacing":["-.05em",".1em",".25em"]
		}
	},
	"layout":{
		"modules":[
			"AspectRatio",
			"BackgroundPosition",
			"BackgroundSize",
			"BorderRadius",
			"BorderStyle",
			"BorderWidth",
			"BoxShadow",
			"Clear",
			"Clearfix",
			"Display",
			"FlexBox",
			"Float",
			"HeightPercentage",
			"HeightScale",
			"HiddenContent",
			"MaxWidth",
			"MinHeightPercentage",
			"NegativeMargins",
			"Outline",
			"Overflow",
			"Position",
			"Rotation",
			"ScreenHeight",
			"Spacing",
			"VerticalAlign",
			"WhiteSpace",
			"WidthPercentage",
			"WidthScale",
			"ZIndex"
		],
		"naming":{
			"backgroundPosition":"bg",
			"borderRadius":"br",
			"borderAll":"ba",
			"borderBottom":"bb",
			"borderLeft":"bl",
			"borderNone":"bn",
			"borderRight":"br",
			"borderStyle":"b--",
			"borderTop":"bt",
			"borderWidth":"bw",
			"circle":"br-100",
			"clearBoth":"cb",
			"clearLeft":"cl",
			"clearNone":"cn",
			"clearRight":"cr",
			"displayNone":"dn",
			"displayBlock":"db",
			"displayInline":"di",
			"displayInlineBlock":"dib",
			"displayInlineTable":"dit",
			"displayTable":"dt",
			"displayTableCell":"dtc",
			"displayTableRow":"dt-row",
			"displayTableRowGroup":"dt-row-group",
			"displayTableColumn":"dt-column",
			"displayTableColumnGroup":"dt-column-group",
			"floatLeft":"fl",
			"floatRight":"fr",
			"floatNone":"fn",
			"heightAuto":"h-auto",
			"heightInherit":"h-inherit",
			"heightScale":"h",
			"heightPercentage":"h-",
			"hiddenContent":"clip",
			"maxWidth":"mw",
			"maxWidthNone":"mw-none",
			"maxWidthFit":"mw-100",
			"minHeightPercentage":"min-h-",
			"marginAll":"ma",
			"marginTop":"mt",
			"marginRight":"mr",
			"marginBottom":"mb",
			"marginLeft":"ml",
			"marginVertical":"mv",
			"marginSides":"mh",
			"marginCenter":"center",
			"negativeMarginAll":"na",
			"negativeMarginTop":"nt",
			"negativeMarginRight":"nr",
			"negativeMarginBottom":"nb",
			"negativeMarginLeft":"nl",
			"paddingAll":"pa",
			"paddingTop":"pt",
			"paddingRight":"pr",
			"paddingBottom":"pb",
			"paddingLeft":"pl",
			"paddingVertical":"pv",
			"paddingSides":"ph",
			"pill":"br-pill",
			"positionAll":"absolute--fill",
			"screenHeight":"vh-",
			"shadow":"shadow-",
			"tableFixed":"dt--fixed",
			"verticalAlignBaseline":"v-base",
			"verticalAlignTop":"v-top",
			"verticalAlignMiddle":"v-mid",
			"verticalAlignBottom":"v-btm",
			"widthScale":"w",
			"widthPercentage":"w-"
		},
		"styles":{
			"widthScale":[
				"1rem",
				"2rem",
				"4rem",
				"8rem",
				"16rem"
			],
			"widthPercentage":[
				"10",
				"20",
				"25",
				"30",
				"33",
				"34",
				"40",
				"50",
				"60",
				"70",
				"75",
				"80",
				"90",
				"100"
			],
			"maxWidth":[
				"1rem",
				"2rem",
				"4rem",
				"8rem",
				"16rem",
				"32rem",
				"48rem",
				"64rem",
				"96rem"
			],
			"heightScale":[
				"1rem",
				"2rem",
				"4rem",
				"8rem",
				"16rem"
			],
			"heightPercentage":[
				"25",
				"50",
				"75",
				"100"
			],
			"minHeightPercentage":[
				"100"
			],
			"screenHeight": [
				"25",
				"50",
				"75",
				"100"
			],
			"borderRadius":[
				".125rem",
				".25rem",
				".5rem",
				"1rem"
			],
			"borderWidth":[
				".125rem",
				".25rem",
				".5rem",
				"1rem",
				"2rem"
			],
			"spacing":[
				".25rem",
				".5rem",
				"1rem",
				"2rem",
				"4rem",
				"8rem",
				"16rem"
			],
			"positions":[
				{"-2":"-2rem"},
				{"-1":"-1rem"},
				{"0":"0"},
				{"1":"1rem"},
				{"2":"2rem"}
			],
			"zIndex":[0,1,2,3,4,5,999,9999],
			"rotations":[
				"45",
				"90",
				"135",
				"180",
				"225",
				"270",
				"315"
			],
			"shadows":[
				"0px 0px 4px 2px rgba( 0, 0, 0, 0.2 )",
				"0px 0px 8px 2px rgba( 0, 0, 0, 0.2 )",
				"2px 2px 4px 2px rgba( 0, 0, 0, 0.2 )",
				"2px 2px 8px 0px rgba( 0, 0, 0, 0.2 )",
				"4px 4px 8px 0px rgba( 0, 0, 0, 0.2 )"
			],
			"flexOrder":"9",
			"aspectRatios":["16x9","4x3","6x4","8x5","7x5","1x1"]
		}
	},
	"media":{
		"queries":[
			{"ns":"@media screen and (min-width: 30em)"},
			{"m":"@media screen and (min-width: 30em) and (max-width: 60em)"},
			{"l":"@media screen and (min-width: 60em)"}
		],
		"isPrefix":false
	},
	"libs":[
		"normalize.css",
		"border-box.css",
		"tachyons/code.css",
		"tachyons/forms.css",
		"tachyons/hovers.css",
		"tachyons/images.css",
		"tachyons/links.css",
		"tachyons/lists.css",
		"tachyons/nested.css",
		"tachyons/opacity.css",
		"tachyons/tables.css",
		"tachyons/z-index.css"
	]
};